# Generated by Django 4.0.4 on 2023-02-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mood',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
