# Generated by Django 4.0.4 on 2023-02-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodlog', '0002_alter_post_mood'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='post',
            name='post_status',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
